### ISSUE TITLE
Some code leads to overflow

### ISSUE THREAD

**Issue by UndefBhvr** [matus-chochlik/mirror#7]
Hi

This issue should be in the reflection branch, but I don't know how to commit there.

When I build with MinGW gcc12, the file

https://github.com/matus-chochlik/llvm-project/blob/reflection/clang/include/clang/Basic/Reflection.h

leads to build failure since there are code like 1UL<<35U, which may cause UB.

Maybe we can use 1ULL<<35U instead.

**Comment by matus-chochlik** [comment]
Fixed
